# Generated by Django 4.2.28 on 2026-02-05 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=32, verbose_name='平台')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='平台商品ID')),
                ('name', models.CharField(max_length=512, verbose_name='商品名称')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='品牌')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('sales_volume', models.IntegerField(blank=True, null=True, verbose_name='销量')),
                ('sales_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='销售额')),
                ('origin', models.CharField(blank=True, max_length=128, verbose_name='产地')),
                ('spec', models.CharField(blank=True, max_length=128, verbose_name='规格')),
                ('url', models.URLField(blank=True, max_length=1024, verbose_name='链接')),
                ('raw_attrs', models.JSONField(blank=True, default=dict, verbose_name='原始属性/标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品（常温牛奶）',
                'verbose_name_plural': '商品（常温牛奶）',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='属性名')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='说明')),
            ],
            options={
                'verbose_name': '产品属性标签',
                'verbose_name_plural': '产品属性标签',
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64, verbose_name='用户标识')),
                ('behavior_type', models.CharField(default='purchase', max_length=32, verbose_name='行为类型')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成交价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='行为时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='core.product')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='用户标识')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('rating', models.SmallIntegerField(blank=True, null=True, verbose_name='评分')),
                ('sentiment', models.SmallIntegerField(blank=True, null=True, verbose_name='情感极性')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='评论时间')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_relations', to='core.product')),
            ],
            options={
                'verbose_name': '商品-属性关联',
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
